import "@/styles/globals.css";
import Head from "next/head";
import { Montserrat } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const monsterrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export default function App({ session,Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Next Spotify </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${monsterrat.variable} font-mont`}>
        <SessionProvider session={session}>
          <Component {...pageProps} />
        </SessionProvider>
      </main>
    </>
  );
}
